friender/appointment/urls.py
from django.urls import path, re_path
from django.views.decorators.cache import cache_page

from .views import *

urlpatterns = [
    path('friends/', cache_page(60 * 15)(FriendListView.as_view()), name='friends'),
    path('establishments/', EstablishmentListView.as_view(), name='establishments'),
    path('hosts/', cache_page(60 * 15)(HostListView.as_view()), name='hosts'),
    path('guests/', GuestListView.as_view(), name='guests'),
    path('user_rating/', UserRatingListView.as_view(), name='user_rating'),
    path('establishment_rating/', EstablishmentRatingListView.as_view(), name='establishment_rating'),
    re_path(r"^user_rating/(?P<id>[\d-]+)$", user_form_rating, name="user_form_rating"),
    re_path(r"^establishment_rating/(?P<id>[\d-]+)$", establishment_form_rating, name="establishment_form_rating"),
    path('create_user/', UserCreateView.as_view(), name='create_user'),
    path('create_appointment/', create_appointment_form, name='create_appointment'),
    path('make_an_order/', make_an_order, name='make_an_order'),
]

friender/friender/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name="friender.html"), name='friender'),
    path('home/', TemplateView.as_view(template_name="home.html"), name='home'),
    path('appointment/', include("appointment.urls")),
    path('api/', include("friender_api.urls")),
    path('api_auth/', include('rest_framework.urls')),
    path('api-token-auth/', CustomAuthToken.as_view()),
    path('__debug__/', include('debug_toolbar.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

friender/appointment/models.py
from django.db import models
from datetime import datetime
from django.core.validators import *
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from django import forms
from django.urls import reverse

STATUS = [
    ('A', 'Available'),
    ('B', 'Busy')
]

SEX = [
    ("M", "Male"),
    ("F", "Female")
]

CATEGORY = [
    ("C", "Cafe"),
    ("R", "Restaurant"),
    ("P", "Pub")
]

HOBBIES = [
    ("S", "Sport"),
    ("T", "Traveling"),
    ("P", "Painting")
]


class Users(models.Model):
    name = models.CharField(max_length=100, verbose_name="Имя")
    surname = models.CharField(max_length=100, verbose_name="Фамилия")
    age = models.PositiveIntegerField(verbose_name="Возраст", validators=[
        MaxValueValidator(90, message='Is too old'),
        MinValueValidator(18, message='Is too young')
    ])
    sex = models.CharField(max_length=1, choices=SEX, verbose_name="Пол")
    email = models.EmailField(null=True, unique=True, verbose_name="Email")
    city = models.CharField(max_length=100, default="Minsk", verbose_name="Город")
    photo = models.ImageField(upload_to="profile_photo", null=True)

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"

    def __str__(self):
        return self.name


class Passport(models.Model):
    passport_id = models.CharField(max_length=40, unique=True, verbose_name="Уникальный номер")
    date_create = models.DateTimeField(auto_created=datetime, verbose_name="Дата создания")
    user = models.OneToOneField("Users", on_delete=models.CASCADE, verbose_name="Пользователь")

    class Meta:
        verbose_name = "Паспорт пользователя"
        verbose_name_plural = "Паспорта пользователей"

    def __str__(self):
        return self.passport_id


class Host(Users):
    max_spend_value = models.PositiveIntegerField(verbose_name="Предложение")
    status = models.CharField(choices=STATUS, max_length=1, default='A')

    def __str__(self):
        return f"{self.name} ({self.max_spend_value})"

    class Meta:
        verbose_name = "Приглашающий"
        verbose_name_plural = "Приглашающие"


class Guest(Users):
    min_bill_value = models.PositiveIntegerField(verbose_name="Желание")

    class Meta:
        verbose_name = "Гость"
        verbose_name_plural = "Гости"

    indexes = [
        models.Index(fields=["name"]),
        models.Index(fields=["min_bill_value"]),
        models.Index(fields=["age]"]),
        models.Index(fields=["name_hobby"])
    ]

    def __str__(self):
        return self.name


class Establishments(models.Model):
    name = models.CharField(max_length=200, verbose_name="Название")
    category = models.CharField(max_length=1, choices=CATEGORY, verbose_name="Категория")
    address = models.CharField(max_length=100, null=True, verbose_name="Адрес")
    phone = models.CharField(max_length=100, null=True, verbose_name="Номер")
    photo = models.ImageField(upload_to="establishment_photo", null=True)

    class Meta:
        verbose_name = "Место"
        verbose_name_plural = "Места"

    indexes = [
        models.Index(fields=["category"]),
        models.Index(fields=["address"]),
    ]

    def __str__(self):
        return self.name


class Hobbies(models.Model):
    name_hobby = models.CharField(max_length=100, verbose_name="Название хобби")
    category = models.CharField(max_length=100, choices=HOBBIES, verbose_name="Категория")
    user = models.ManyToManyField("Users", verbose_name="Пользователь")

    class Meta:
        verbose_name = "Хобби"
        verbose_name_plural = "Хобби"

    def __str__(self):
        return str(self.name_hobby)


class Appointments(models.Model):
    host = models.ForeignKey("Host", on_delete=models.CASCADE, null=True, verbose_name="Приглашающий")
    guest = models.ForeignKey("Guest", on_delete=models.CASCADE, null=True, verbose_name="Приглашённый")
    establishments = models.ForeignKey("Establishments", on_delete=models.CASCADE, verbose_name="Место")

    class Meta:
        verbose_name = "Свидание"
        verbose_name_plural = "Свидания"

    def __str__(self):
        return f"Cвидание между {self.host} и {self.guest}"


class Rating(models.Model):
    rating = models.PositiveIntegerField(verbose_name="Рейтинг", validators=[
        MaxValueValidator(5, message='Введите значение между 1 - 5'),
        MinValueValidator(1, message='Введите значение между 1 - 5')
    ])
    description = models.CharField(max_length=100, verbose_name="Описание")

    class Meta:
        abstract = True

    def __str__(self):
        return str(self.rating)


class UserRating(Rating):
    user = models.ForeignKey("Users", on_delete=models.CASCADE, verbose_name="Пользователь")

    class Meta:
        verbose_name = "Рейтинг пользователя"
        verbose_name_plural = "Рейтинг пользователей"

    def __str__(self):
        return str(self.rating)


class EstablishmentsRating(Rating):
    establishment = models.ForeignKey("Establishments", on_delete=models.CASCADE, verbose_name="Место")

    class Meta:
        verbose_name = "Рейтинг места"
        verbose_name_plural = "Рейтинг мест"

    def __str__(self):
        return str(self.establishment)


class Order(models.Model):
    price = models.PositiveIntegerField(verbose_name="Стоимость")
    date_order = models.CharField(max_length=100, verbose_name="Комментарий к заказу")
    appointment = models.OneToOneField("Appointments", on_delete=models.CASCADE, verbose_name="Свидание")

    class Meta:
        verbose_name = "Заказ"
        verbose_name_plural = "Заказы"


class PlaceQueue(models.Model):
    value = models.PositiveIntegerField(verbose_name="значение")

friender/appointment/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from django.core.validators import *
from .models import *

SEX = [
    ("M", "Male"),
    ("F", "Female")
]


class UserFormRating(forms.ModelForm):
    class Meta:
        model = UserRating
        fields = ['rating', 'description']
        widgets = {
            "description": forms.Textarea(attrs={'class': 'form-input'}),
        }


class EstablishmentFormRating(forms.ModelForm):
    class Meta:
        model = EstablishmentsRating
        fields = ['rating', 'description']
        widgets = {
            "description": forms.Textarea(attrs={'class': 'form-input'}),
        }


class CreateUserForm(forms.ModelForm):
    class Meta:
        model = Users
        fields = '__all__'
        exclude = ('email',)


class CreateAppointmentForm(forms.Form):
    host = forms.ChoiceField(choices=Host.objects.values_list('id', 'name'))
    place = forms.ChoiceField(choices=Establishments.objects.values_list('id', 'name'))


class MakeAnOrder(forms.ModelForm):
    class Meta:
        model = Order
        fields = '__all__'

friender/appointment/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.http import HttpResponse
from django.views import View
from .forms import *
from .models import *
from django.db import transaction
from django.core.paginator import Paginator
from django.views.generic import *
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.core.cache import cache

from django.urls import reverse_lazy


class FriendListView(LoginRequiredMixin, ListView):
    login_url = "/admin/login"
    template_name = "friends.html"
    model = Users
    context_object_name = "users"
    paginate_by = 5
    cache.clear()


class EstablishmentListView(PermissionRequiredMixin, ListView):
    permission_required = "appointment.view_establishments"
    model = Establishments
    template_name = "establishments.html"
    context_object_name = "establishments"
    paginate_by = 5
    permission_denied_message = "Отказано в доступе"
    raise_exception = True

    def get_permission_denied_message(self):
        """
        Override this method to override the permission_denied_message attribute.
        """
        return self.permission_denied_message


class HostListView(ListView):
    template_name = "hosts.html"
    model = Host
    context_object_name = "hosts"
    paginate_by = 5
    cache.clear()


class GuestListView(ListView):
    template_name = "guests.html"
    model = Guest
    context_object_name = "guests"
    paginate_by = 5


class UserRatingListView(ListView):
    template_name = "user_rating.html"
    model = UserRating
    context_object_name = "ratings"
    paginate_by = 5


def establishment_form_rating(request, **kwargs):
    establishment_id = int(kwargs['id'])
    context = {}
    if request.method == "POST":
        form = EstablishmentFormRating(request.POST)
        context["form"] = form
        if form.is_valid():
            EstablishmentsRating.objects.create(
                establishment_id=establishment_id,
                rating=request.POST['rating'],
                description=request.POST['description'],
            )
            return HttpResponseRedirect("/appointment/establishment_rating")
    else:
        form = EstablishmentFormRating()
        context["form"] = form
    return render(request, "establishments_form_rating.html", context=context)


def user_form_rating(request, **kwargs):
    user_id = int(kwargs['id'])
    context = {}
    if request.method == "POST":
        form = UserFormRating(request.POST)
        context["form"] = form
        if form.is_valid():
            UserRating.objects.create(
                user_id=user_id,
                rating=request.POST['rating'],
                description=request.POST['description'],
            )
            return HttpResponseRedirect("/appointment/user_rating")
    else:
        form = UserFormRating()
        context["form"] = form
    return render(request, "user_form_rating.html", context=context)


class EstablishmentRatingListView(ListView):
    template_name = "establishment_rating.html"
    model = EstablishmentsRating
    context_object_name = "ratings"
    paginate_by = 5


class UserCreateView(CreateView):
    template_name = "create_user_form.html"
    model = Users
    fields = ["name", "surname", "age", "sex", "email", "city", "photo"]
    success_url = "../friends"


def create_appointment_form(request):
    context = {}
    if request.method == "POST":
        form = CreateAppointmentForm(request.POST)
        context["form"] = form
        guest = Guest.objects.all().order_by('?')[0]
        if form.is_valid():
            host_id = int(request.POST['host'][0])
            place_id = int(request.POST['place'][0])

            establishments = Establishments.objects.get(id=place_id)
            hosts = Host.objects.select_for_update().filter(users_ptr_id=host_id)
            with transaction.atomic():
                for host in hosts:
                    if host.status == 'A' and host:
                        host.status = 'B'
                        host.save()
                        Appointments.objects.create(
                            host=host,
                            guest=Guest.objects.get(id=guest.id),
                            establishments=establishments
                        )
                    else:
                        raise ValueError("Пользователь уже занят")
            return HttpResponseRedirect("/appointment/friends")
    else:
        form = CreateAppointmentForm()
        context["form"] = form
    return render(request, "create_appointment_form.html", context=context)


def make_an_order(request):
    context = {}
    if request.method == "POST":
        form = MakeAnOrder(request.POST)
        context["form"] = form
        if form.is_valid():
            appointment = (request.POST['appointment'][0])
            price = int(request.POST['price'])
            host = Host.objects.get(appointments=appointment)
            with transaction.atomic():
                if host.max_spend_value >= price:
                    host.max_spend_value = host.max_spend_value - price
                    host.save()
                    form.save()
                else:
                    raise ValueError("Недостаточно средств")
                return HttpResponseRedirect("/appointment/friends")
    else:
        form = MakeAnOrder()
        context["form"] = form
    return render(request, "make_an_order.html", context=context)

friender/appointment/templates/create_appointment_form.html
{% extends "base.html" %}
{% block title %} Создание свидания | Знакомься, встречайся, заводи друзей - Friender {% endblock %}
{% block content %}
{% load crispy_forms_tags %}
    <form method="POST">
        {{form|crispy}}
        {% csrf_token %}
        <button type="submit" class="btn btn-primary">Отправить</button>
    </form>
{% endblock %}

friender/appointment/templates/create_user_form.html
{% extends "base.html" %}
{% block title %} Создание пользователя | Знакомься, встречайся, заводи друзей - Friender {% endblock %}
{% block content %}
{% load crispy_forms_tags %}
    <form method="POST" enctype="multipart/form-data">
        {{form|crispy}}
        {% csrf_token %}
        <button type="submit" class="btn btn-primary">Отправить</button>
    </form>
{% endblock %}

friender/appointment/templates/establishment_rating.html
{% extends "base.html" %}
{% block title %} Отзывы о заведениях | Знакомься, встречайся, заводи друзей - Friender {% endblock %}
{% block content %}
    <table class="table">
        <thead>
        <tr>
            <th scope="col">Название</th>
            <th scope="col">Рейтинг</th>
            <th scope="col">Отзыв</th>
        </tr>
        </thead>
        <tbody>
        {% for rating in ratings %}
            <tr>
                <td>{{ rating.establishment }} </td>
                <td>{{ rating.rating }}</td>
                <td>{{ rating.description }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <nav aria-label="...">
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1">First</a>
                </li>
            {% endif %}
            {% for num in page_obj.paginator.page_range %}
                {% if page_obj.number == num %}
                    <li class="page-item active" aria-current="page">
                        <a class="page-link" href="?page={{ num }}"> {{ num }}</a>
                    </li>
                {% elif num > page_obj.paginator.number|add:'-3' and num < page_obj.paginator.number|add:'3' %}
                    <li class="page-item" aria-current="page">
                        <a class="page-link" href="?page={{ num }}"> {{ num }}</a>
                    </li>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
                </li>
            {% endif %}
            </li>
        </ul>
    </nav>
{% endblock %}

friender/appointment/templates/establishments.html
{% extends "base.html" %}
{% block title %} Заведения | Знакомься, встречайся, заводи друзей - Friender {% endblock %}
{% block content %}
    <table class="table">
        {% load cache %}
        {% cache 1200 columns %}
            <thead>
            <tr>
                <th scope="col">Название</th>
                <th scope="col">Категория</th>
                <th scope="col">Адрес</th>
                <th scope="col">Телефон</th>
            </tr>
            </thead>
        {% endcache %}
        <tbody>
        {% for establishment in establishments %}
            <tr>
                <td><a href="{% url 'establishment_form_rating' id=establishment.id %}">{{ establishment.name }}</a>
                </td>
                <td>{{ establishment.category }}</td>
                <td>{{ establishment.address }}</td>
                <td>{{ establishment.phone }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <nav aria-label="...">
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1">First</a>
                </li>
            {% endif %}
            {% for num in page_obj.paginator.page_range %}
                {% if page_obj.number == num %}
                    <li class="page-item active" aria-current="page">
                        <a class="page-link" href="?page={{ num }}"> {{ num }}</a>
                    </li>
                {% elif num > page_obj.paginator.number|add:'-3' and num < page_obj.paginator.number|add:'3' %}
                    <li class="page-item" aria-current="page">
                        <a class="page-link" href="?page={{ num }}"> {{ num }}</a>
                    </li>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
                </li>
            {% endif %}
            </li>
        </ul>
    </nav>
{% endblock %}

friender/appointment/templates/establishments_form_rating.html
{% extends "base.html" %}
{% block title %} Поделитесь своими впечатлениями | Знакомься, встречайся, заводи друзей - Friender {% endblock %}
{% block content %}
{% load crispy_forms_tags %}
    <form method="POST">
        {{form|crispy}}
        {% csrf_token %}
        <button type="submit" class="btn btn-primary">Отправить</button>
    </form>
{% endblock %}

friender/appointment/templates/friends.html
{% extends "base.html" %}
{% block title %} Друзья | Знакомься, встречайся, заводи друзей - Friender {% endblock %}
{% block content %}
    <table class="table">
        {% load cache %}
        {% cache 1200 columns %}
            <thead>
            <tr>
                <th scope="col">Имя</th>
                <th scope="col">Фамилия</th>
                <th scope="col">Возраст</th>
                <th scope="col">Пол</th>
                <th scope="col">Email</th>
                <th scope="col">Город</th>
                <th scope="col">Хобби</th>
                <th scope="col">Рейтинг</th>
                <th scope="col">Фото</th>
            </tr>
            </thead>
        {% endcache %}
        <tbody>
        {% for friend in page_obj %}
            <tr>
                <td>{{ friend.name }}</td>
                <td>{{ friend.surname }}</td>
                <td>{{ friend.age }}</td>
                <td>{{ friend.sex }}</td>
                {% if friend.email %}
                    <td>{{ friend.email }}</td>
                {% else %}
                    <td></td>
                {% endif %}
                <td>{{ friend.city }}</td>
                <td>
                    {% for hobby in friend.hobbies_set.all %}
                        {{ hobby }},
                    {% endfor %}
                </td>
                <td>
                    {% for rating in friend.userrating_set.all %}
                        {{ rating }},
                    {% endfor %}
                </td>
                <td>{% if friend.photo %}<img style="max-height: 100px" src="{{ friend.photo.url }}"> {% endif %}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <nav aria-label="...">
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1">First</a>
                </li>
            {% endif %}
            {% for num in page_obj.paginator.page_range %}
                {% if page_obj.number == num %}
                    <li class="page-item active" aria-current="page">
                        <a class="page-link" href="?page={{ num }}"> {{ num }}</a>
                    </li>
                {% elif num > page_obj.paginator.number|add:'-3' and num < page_obj.paginator.number|add:'3' %}
                    <li class="page-item" aria-current="page">
                        <a class="page-link" href="?page={{ num }}"> {{ num }}</a>
                    </li>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
                </li>
            {% endif %}
        </ul>
    </nav>
{% endblock %}

friender/appointment/templates/guests.html
{% extends "base.html" %}
{% block title %} Гости | Знакомься, встречайся, заводи друзей - Friender {% endblock %}
{% block content %}
    <table class="table">
        {% load cache %}
        {% cache 1200 columns %}
            <thead>
            <tr>
                <th scope="col">Имя</th>
                <th scope="col">Фамилия</th>
                <th scope="col">Возраст</th>
                <th scope="col">Пол</th>
                <th scope="col">Email</th>
                <th scope="col">Город</th>
            </tr>
            </thead>
        {% endcache %}
        <tbody>
        {% for guest in guests %}
            <tr>
                <td>{{ guest.name }}</td>
                <td>{{ guest.surname }}</td>
                <td>{{ guest.age }}</td>
                <td>{{ guest.sex }}</td>
                <td>{{ guest.email }}</td>
                <td>{{ guest.city }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <nav aria-label="...">
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1">First</a>
                </li>
            {% endif %}
            {% for num in page_obj.paginator.page_range %}
                {% if page_obj.number == num %}
                    <li class="page-item active" aria-current="page">
                        <a class="page-link" href="?page={{ num }}"> {{ num }}</a>
                    </li>
                {% elif num > page_obj.paginator.number|add:'-3' and num < page_obj.paginator.number|add:'3' %}
                    <li class="page-item" aria-current="page">
                        <a class="page-link" href="?page={{ num }}"> {{ num }}</a>
                    </li>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
                </li>
            {% endif %}
            </li>
        </ul>
    </nav>
{% endblock %}

friender/appointment/templates/hosts.html
{% extends "base.html" %}
{% block title %} Приглашающие | Знакомься, встречайся, заводи друзей - Friender  {% endblock %}
{% block content %}
    <table class="table">
        {% load cache %}
        {% cache 1200 columns %}
            <thead>
            <tr>
                <th scope="col">Имя</th>
                <th scope="col">Фамилия</th>
                <th scope="col">Возраст</th>
                <th scope="col">Пол</th>
                <th scope="col">Email</th>
                <th scope="col">Город</th>
            </tr>
            </thead>
        {% endcache %}
        <tbody>
        {% for host in hosts %}
            <tr>
                <td>{{ host.name }}</td>
                <td>{{ host.surname }}</td>
                <td>{{ host.age }}</td>
                <td>{{ host.sex }}</td>
                <td>{{ host.email }}</td>
                <td>{{ host.city }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <nav aria-label="...">
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1">First</a>
                </li>
            {% endif %}
            {% for num in page_obj.paginator.page_range %}
                {% if page_obj.number == num %}
                    <li class="page-item active" aria-current="page">
                        <a class="page-link" href="?page={{ num }}"> {{ num }}</a>
                    </li>
                {% elif num > page_obj.paginator.number|add:'-3' and num < page_obj.paginator.number|add:'3' %}
                    <li class="page-item" aria-current="page">
                        <a class="page-link" href="?page={{ num }}"> {{ num }}</a>
                    </li>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
                </li>
            {% endif %}
        </ul>
    </nav>
{% endblock %}

friender/appointment/templates/make_an_order.html
{% extends "base.html" %}
{% block content %}
{% block title %} Оформление заказа | Знакомься, встречайся, заводи друзей - Friender {% endblock %}
{% load crispy_forms_tags %}
    <form method="POST">
        {{form|crispy}}
        {% csrf_token %}
        <button type="submit" class="btn btn-primary">Заказать</button>
    </form>
{% endblock %}

friender/appointment/templates/user_form_rating.html
{% extends "base.html" %}
{% block content %}
{% block title %} Поделитесь своими впечатлениями | Знакомься, встречайся, заводи друзей - Friender {% endblock %}
{% load crispy_forms_tags %}
    <form method="POST">
        {{form|crispy}}
        {% csrf_token %}
        <button type="submit" class="btn btn-primary">Отправить</button>
    </form>
{% endblock %}

friender/appointment/templates/user_rating.html
{% extends "base.html" %}
{% block title %} Отзывы о пользователях | Знакомься, встречайся, заводи друзей - Friender {% endblock %}
{% block content %}
    <table class="table">
        <thead>
        <tr>
            <th scope="col">Имя</th>
            <th scope="col">Рейтинг</th>
            <th scope="col">Отзыв</th>
        </tr>
        </thead>
        <tbody>
        {% for rating in ratings %}
            <tr>
                <td>{{ rating.user.name }} {{ rating.user.surname }}</td>
                <td>{{ rating.rating }}</td>
                <td>{{ rating.description }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <nav aria-label="...">
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1">First</a>
                </li>
            {% endif %}
            {% for num in page_obj.paginator.page_range %}
                {% if page_obj.number == num %}
                    <li class="page-item active" aria-current="page">
                        <a class="page-link" href="?page={{ num }}"> {{ num }}</a>
                    </li>
                {% elif num > page_obj.paginator.number|add:'-3' and num < page_obj.paginator.number|add:'3' %}
                    <li class="page-item" aria-current="page">
                        <a class="page-link" href="?page={{ num }}"> {{ num }}</a>
                    </li>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
                </li>
            {% endif %}
            </li>
        </ul>
    </nav>
{% endblock %}